# Generated by Django 3.0.2 on 2020-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='address',
            field=models.CharField(default='SOME STRING', max_length=64),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='district',
            field=models.CharField(default='SOME STRING', max_length=64),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='mobnumber',
            field=models.CharField(default='Some Number', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=32),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('FMR', 'Farmer'), ('SPL', 'Supplier'), ('RTL', 'Retailer')], default='FMR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='op_land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
